# server port config
server:
  port: 8001
  
# oracle driver config
spring:
  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    url: jdbc:oracle:thin:@localhost:1521:xe
    username : C##DOBEBEST
    password : DOBEBEST
    hikari:
      auto-commit: false



    